// Copyright 2017 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Please note that this file is autogenerated by "npm run postversion" script.

import {VersionInfo} from '@api/root.ui';

// prettier-ignore
export const version: VersionInfo = {
  'dirty': false,
  'raw': 'v2.4.1-rc1-9-gb5ec07f',
  'hash': 'gb5ec07f',
  'distance': 9,
  'tag': 'v2.4.1-rc1',
  'semver': {
    'options': {
      'includePrerelease': false,
      'loose': false
    },
    'loose': false,
    'raw': 'v2.4.1-rc1',
    'major': 2,
    'minor': 4,
    'patch': 1,
    'prerelease': [
      'rc1'
    ],
    'build': [],
    'version': '2.4.1-rc1'
  },
  'suffix': '9-gb5ec07f',
  'semverString': '2.4.1-rc1+9.gb5ec07f',
  'packageVersion': '2.4.1'
};
